import { Widget } from './types';

export const initialWidgetMap: Record<string, Widget> = {
  irLnnOIu: {
    id: 'irLnnOIu',
    title: 'Recently visited',
    infoLink: true,
    footer: 'View all services',
    big: true,
    isAdded: true,
  },
  mCsUr_BB: {
    id: 'mCsUr_BB',
    title: 'Welcome to AWS',
    infoLink: false,
    footer: null,
    big: false,
    isAdded: true,
  },
  YJ93V_Wj: {
    id: 'YJ93V_Wj',
    title: 'AWS Health',
    infoLink: true,
    footer: 'Go to AWS Health',
    big: false,
    isAdded: true,
  },
  VBqQM5zf: {
    id: 'VBqQM5zf',
    title: 'Cost and usage',
    infoLink: true,
    footer: 'Go to AWS Cost Management',
    big: true,
    isAdded: true,
  },
  RIyILDAp: {
    id: 'RIyILDAp',
    title: 'Build a solution',
    infoLink: true,
    footer: null,
    big: true,
    isAdded: true,
  },
  LCanROpO: {
    id: 'LCanROpO',
    title: 'Trusted Advisor',
    infoLink: true,
    footer: 'Go to Trusted Advisor',
    big: false,
    isAdded: true,
  },
  dXrePkX2: {
    id: 'dXrePkX2',
    title: 'Explore AWS',
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  '2APJvsb7': {
    id: '2APJvsb7',
    title: 'Latest announcements',
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  '2BnJvsb6': {
    id: '2BnJvsb6',
    title: 'Recent AWS blog posts',
    infoLink: true,
    footer: null,
    big: false,
    isAdded: true,
  },
  fdXNnvZl: {
    id: 'fdXNnvZl',
    title: 'Applications',
    infoLink: true,
    footer: 'Go to Application Manager',
    big: true,
    isAdded: true,
  },
  WzeJcY2w: {
    id: 'WzeJcY2w',
    title: 'Security Hub',
    infoLink: true,
    footer: 'Go to Security Hub',
    big: false,
    isAdded: true,
  },

  /* Not added */
  '3EwHwCXh': {
    id: '3EwHwCXh',
    title: 'Not Added 1',
    infoLink: true,
    footer: null,
    big: false,
    isAdded: false,
  },
  P5dCD5NV: {
    id: 'P5dCD5NV',
    title: 'Not Added 2',
    infoLink: true,
    footer: null,
    big: false,
    isAdded: false,
  },
  'yY4l_n-R': {
    id: 'yY4l_n-R',
    title: 'Not Added 3',
    infoLink: true,
    footer: 'Go to Application Manager',
    big: true,
    isAdded: false,
  },
  G8nLueuD: {
    id: 'G8nLueuD',
    title: 'Not Added 4',
    infoLink: true,
    footer: 'Go to Security Hub',
    big: false,
    isAdded: false,
  },
};
